name: Secrets Scan

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog
        run: |
          trufflehog --regex --entropy=True --json . > trufflehog_output.json || true

      - name: Send Discord Alert if Secrets Found
        if: always()
        run: |
          if [ -s trufflehog_output.json ]; then
            curl -H "Content-Type: application/json" \
              -d "{\"content\": \"⚠️ Secret detected in repo $GITHUB_REPOSITORY on branch $GITHUB_REF by $GITHUB_ACTOR\"}" \
              https://discord.com/api/webhooks/1400516673609531472/o8Xh4GT1Fgh2MiYKmJiTJZkphjPhgnWnIy63OHNkueR4-a8c-CZWdg8ZqvkvTVoQdgmB
          fi

  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          curl -s https://raw.githubusercontent.com/gitleaks/gitleaks/main/scripts/install.sh | bash

      - name: Run Gitleaks
        run: gitleaks detect --source . --verbose --exit-code 1
