name: Secrets Scan

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog
        run: trufflehog --regex --entropy=True --json .

  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64
          chmod +x gitleaks-linux-amd64
          sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks

      - name: Run Gitleaks
        run: gitleaks detect --source . --verbose --exit-code 1
